[package]
name = "stream-td"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy={version = "0.16.1"}
bevy-inspector-egui = "0.32.0"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.99"
serde_json = "1.0.142"
