[package]
name = "stream-td"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy={version = "0.16.1"}
bevy-inspector-egui = "0.32.0"
rand = "0.9.2"
bytemuck = "1.23.1"

[build-dependencies]
fs_extra = "1.3.0"